# Generated by Django 4.1.7 on 2023-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayFit', '0002_gexercise_hexercise_membership_pt_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight loss'), ('muscle_building', 'Muscle building'), ('endurance_training', 'Endurance training'), ('flexibility_training', 'Flexibility training')], max_length=50)),
                ('workout_frequency', models.PositiveIntegerField()),
                ('workout_duration', models.PositiveIntegerField()),
                ('workout_location', models.CharField(max_length=50)),
                ('available_equipment', models.CharField(max_length=100)),
                ('health_concerns', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
