# Generated by Django 4.1.7 on 2023-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayFit', '0004_delete_userpreference_gexercise_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gexercise',
            name='video_link',
        ),
        migrations.AddField(
            model_name='gexercise',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
