# Generated by Django 4.1.7 on 2023-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayFit', '0005_remove_gexercise_video_link_gexercise_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.BigIntegerField(null=True)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('cnumber', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pt_exercises',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='pt_exercises',
            name='muscle_group',
        ),
        migrations.RemoveField(
            model_name='pt_exercises',
            name='name',
        ),
    ]
