# Generated by Django 4.1.7 on 2023-04-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StayFit', '0006_checkout_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
