# Generated by Django 4.1.7 on 2023-04-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayFit', '0007_delete_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexercise',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='s_exercise',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='yoga',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
